---
- name: Docker Configuration Setup
  hosts: node1,node2,node3
  become: yes

  vars:
    insecure_registry: "registry.medai-system.svc.cluster.local:5000"

  tasks:
    - name: Ensure /etc/docker directory exists
      file:
        path: /etc/docker
        state: directory
        mode: '0755'

    - name: Create /etc/docker/daemon.json if not exists
      file:
        path: /etc/docker/daemon.json
        state: touch
        mode: '0644'

    - name: Configure Docker daemon.json for insecure registry
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "registry-mirrors": ["http://registry.medai-system.svc.cluster.local:5000"],
            "insecure-registries": ["{{ insecure_registry }}", "registry.medai-system.svc.cluster.local:5000"]
          }
        owner: root
        group: root
        mode: '0644'

    - name: Restart Docker service to apply changes
      systemd:
        name: docker
        state: restarted
        enabled: yes

    - name: Enable Docker service on boot
      systemd:
        name: docker
        enabled: yes

    - name: Add user 'cc' to Docker group
      user:
        name: cc
        groups: docker
        append: yes

    - name: Verify Docker group membership for user 'cc'
      command: id cc
      register: cc_id

    - name: Show user groups
      debug:
        msg: "{{ cc_id.stdout }}"

    - name: Verify Docker installation
      command: docker --version
      register: docker_version

    - name: Show Docker version
      debug:
        msg: "Docker version: {{ docker_version.stdout }}"
