---
- name: Disable and Mask firewalld
  hosts: all
  become: yes

  tasks:
    - name: Stop firewalld service
      systemd:
        name: firewalld
        state: stopped
        enabled: no

    - name: Mask firewalld service
      systemd:
        name: firewalld
        masked: yes

- name: Set up insecure registry for Docker
  hosts: node1,node2,node3
  become: yes

  vars:
    insecure_registry: "registry.medai-system.svc.cluster.local:5000"

  tasks:

    - name: Ensure /etc/docker directory exists
      file:
        path: /etc/docker
        state: directory
        mode: '0755'

    - name: Create /etc/docker/daemon.json if not exists
      file:
        path: /etc/docker/daemon.json
        state: touch
        mode: '0644'

    - name: Configure Docker daemon.json for insecure registry
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "registry-mirrors": ["http://registry.medai-system.svc.cluster.local:5000"],
            "insecure-registries": ["{{ insecure_registry }}", "registry.medai-system.svc.cluster.local:5000"]
          }
        owner: root
        group: root
        mode: '0644'

    - name: Restart Docker to apply changes
      systemd:
        name: docker
        state: restarted

    - name: Enable Docker on boot
      systemd:
        name: docker
        enabled: yes

- name: Add User to Docker Group
  hosts: node1,node2,node3
  become: yes

  vars:
    ansible_user: cc

  tasks:
    - name: Add user 'cc' to docker group
      user:
        name: cc
        groups: docker
        append: yes

    - name: Restart Docker
      systemd:
        name: docker
        state: restarted
        enabled: yes

    - name: Verify Docker group membership for user 'cc'
      command: id cc
      register: cc_id

    - name: Show user groups
      debug:
        msg: "{{ cc_id.stdout }}"

