apiVersion: apps/v1
kind: Deployment
metadata:
  name: project44-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project44-minio
  template:
    metadata:
      labels:
        app: project44-minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio
          args:
            - server
            - /data
            - "--console-address"
            - ":9001"
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: accesskey
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: secretkey
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: project44-minio
spec:
  selector:
    app: project44-minio
  ports:
    - port: 9000
      targetPort: 9000
    - port: 9001
      targetPort: 9001
  type: ClusterIP
