- name: Add Project44 platform to ArgoCD
  hosts: project44-node1
  become: yes
  tasks:
    - name: Set external IP
      set_fact:
        external_ip: "{{ hostvars[inventory_hostname]['ansible_host'] }}"

    - name: Ensure MinIO credentials secret exists
      shell: |
        kubectl get secret minio-credentials -n project44-platform || \
        kubectl create secret generic minio-credentials \
          --from-literal=accesskey=project44admin \
          --from-literal=secretkey=project44secret \
          -n project44-platform
      args:
        executable: /bin/bash

    - name: Create ArgoCD application for Project44 platform
      command: >
        argocd app create project44-platform \
        --repo https://github.com/Shrey12202/MedAI-Scalable-Diagnosis-with-Machine-Learning.git \
        --path k8s/platform \
        --dest-server https://kubernetes.default.svc \
        --dest-namespace project44-platform \
        --helm-set-string mlflow.externalIP="{{ external_ip }}" \
        --helm-set-string minio.externalIP="{{ external_ip }}" \
        --sync-policy automated
      register: create_output
      failed_when: false

    - name: Sync ArgoCD application (if not auto-syncing)
      command: >
        argocd app sync project44-platform
      when: "'application ' not in create_output.stdout"
