apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: initial-build-
spec:
  entrypoint: initial-build-flow
  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

  templates:
  - name: initial-build-flow
    steps:
      - - name: clone-repo
          template: git-clone
      - - name: kaniko-build
          template: kaniko

  - name: git-clone
    container:
      image: alpine/git
      command: [sh, -c]
      args:
        - |
          MAX_RETRIES=5
          i=1

          while [ $i -le $MAX_RETRIES ]; do
            echo "Attempt $i of $MAX_RETRIES: Cloning repo..."
            git clone --branch main https://github.com/your-repo/initial-project.git /mnt/workspace && break
            echo "Git clone failed. Retrying in 5 seconds..."
            i=$((i + 1))
            sleep 5
          done

          if [ ! -d /mnt/workspace/.git ]; then
            echo "Git clone failed after $MAX_RETRIES attempts."
            exit 1
          fi
      volumeMounts:
      - name: workdir
        mountPath: /mnt/workspace

  - name: kaniko
    container:
      image: gcr.io/kaniko-project/executor:latest
      args:
        - --dockerfile=/mnt/workspace/Dockerfile
        - --context=/mnt/workspace
        - --destination=registry.medai-system.svc.cluster.local:5000/initial-project:staging-1.0.0
        - --destination=registry.medai-system.svc.cluster.local:5000/initial-project:canary-1.0.0
        - --destination=registry.medai-system.svc.cluster.local:5000/initial-project:production-1.0.0
        - --insecure
      volumeMounts:
        - name: workdir
          mountPath: /mnt/workspace

