apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deploy-container-image
spec:
  entrypoint: deploy
  arguments:
    parameters:
    - name: environment
    - name: model-version

  templates:
  - name: deploy
    inputs:
      parameters:
      - name: environment
      - name: model-version
    container:
      image: "your-docker-image:latest"
      command: [sh, -c]
      args:
        - |
          echo "Deploying model {{inputs.parameters.model-version}} to {{inputs.parameters.environment}}..."
          tag="{{inputs.parameters.environment}}-1.0.{{inputs.parameters.model-version}}"
          app_name="gourmetgram-{{inputs.parameters.environment}}"

          # Login to ArgoCD
          argocd login argocd-server.argocd.svc.cluster.local \
            --username admin \
            --password "$ARGOCD_PASSWORD" \
            --insecure

          # Set the application image tag for deployment
          argocd app set "$app_name" --helm-set-string image.tag=$tag

          # Sync the application to apply the changes
          argocd app sync "$app_name"

          echo "Deployment of model version {{inputs.parameters.model-version}} to environment {{inputs.parameters.environment}} is complete."

    env:
      - name: ARGOCD_PASSWORD
        valueFrom:
          secretKeyRef:
            name: argocd-initial-admin-secret
            key: password

