name: production

services:
  fastapi_server:
    build:
      context: ../fastapi_pt
      dockerfile: Dockerfile
    container_name: fastapi_server
    ports:
      - "5000:5000"  # for HTTP requests 8000 hatu
    networks:
      - production_net
    depends_on:
      - minio

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ':9001'
    networks:
      - production_net

  minio-init:
    image: minio/mc
    container_name: minio_init
    depends_on:
      - minio
    restart: "no"
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set myminio http://minio:9000 minioadmin minioadmin &&
      mc mb -p myminio/production || echo 'Bucket already exists'
      "
    networks:
      - production_net

networks:
  production_net:
    external: true

volumes:
  minio_data:
