global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'mlflow'
    static_configs:
      - targets: ['129.114.27.181:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'chexpert_training_pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'fastapi'
    metrics_path: /metrics
    static_configs:
      - targets: ['fastapi_server:5000']  # update name if needed

  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['minio:9000']

  - job_name: 'airflow'
    metrics_path: /admin/metrics
    static_configs:
      - targets: ['airflow-webserver:8080']