# app/Dockerfile
FROM python:3.9-slim

WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    pillow \
    torch \
    torchvision \
    mlflow \
    jinja2

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
